#!/usr/bin/env python3
"""
Generate a compose file with N workers for the state-based arm.

The script writes `docker-compose.c2.parallel.yml`, declaring services
`simulator-0..N-1` on consecutive ports, each started with

    command: uvicorn Simulator.c2.server:app --host 0.0.0.0 --port 8000

and carrying the `--speed-scale` passed on the command line. It sits beside
`gen_parallel_compose.py`, which generates the same file for the DNN arm.

Usage:
    python gen_c2_compose.py            # 4 workers (ports 8000-8003)
    python gen_c2_compose.py 2 --speed-scale 0.6

Then:
    docker compose -f docker-compose.c2.parallel.yml up --build
    # and on the client side:  NUM_WORKERS=4
"""
from __future__ import annotations

import argparse
import os

IMAGE_TAG = "paologinefra/se2rp-simulator"
BASE_PORT = 8000

HEADER = """\
# --- GENERATED by gen_c2_compose.py -- do not edit by hand -------------------
# {n} workers of the state-based arm on host ports {base}..{last} (container: always 8000).
#
# The state-based controller shared with MetaDrive and CARLA drives here, so
# the controller is the same across the backends.
#
# Start:  docker compose -f {out} up --build
# Client: NUM_WORKERS={n}
#
# Throughput against fidelity. Measured on Udacity: 20.8 Hz with 1 container,
# 8.5 Hz with 4, because the Unity instances contend for the CPU. The controller
# compensates (its steering limit is in units/second, converted with the real
# dt), but the control rate stays a confounder against MetaDrive and CARLA,
# where it is exact by construction. Prefer 1 worker for the comparison
# campaign, 4 for exploratory runs.
services:
"""

SERVICE = """\
  simulator-{i}:
    platform: linux/amd64
{build}    image: {image}
    container_name: se2rp-c2-{i}
    # `command` replaces the ENTIRE CMD of the Dockerfile, which does more than
    # launch uvicorn: it starts Xvfb first and exports DISPLAY=:99.
    #
    # Unity is a graphical application and demands a display even headless:
    # without Xvfb the process starts but cannot create the GL context, never
    # connects to the socket.io server, and the container sits forever on
    # "sleep...and repeat to connect" with no explicit error.
    #
    # So the whole bootstrap is replicated here, changing only the uvicorn
    # module. If the Dockerfile's CMD ever changes, this must change too.
    #
    # `$$` and not `$`: in a compose file `${{VAR}}` is expanded by Docker on the
    # HOST, where XVFB_RESOLUTION does not exist. `$$` passes it literally to
    # /bin/sh, which resolves it inside the container against the Dockerfile
    # ENV.
    command: '/bin/sh -c "rm -f /tmp/.X99-lock; Xvfb :99 -screen 0 $${{XVFB_RESOLUTION:-320x240x24}} -ac +extension GLX +extension RANDR +render -noreset & sleep 3 && export DISPLAY=:99 && uvicorn Simulator.c2.server:app --host 0.0.0.0 --port 8000"'
    ports:
      - "{host_port}:8000"
    environment:
      - LK_SPEED_SCALE={speed_scale}
      - LK_STEERING_SIGN={steering_sign}
      - LK_OBS_LATENCY={obs_latency}
      - LK_OBS_LAG_TAU={obs_lag_tau}
      - LK_STEER_NOISE={steer_noise}
    stdin_open: true
    tty: true
    restart: unless-stopped
{depends}"""

BUILD_BLOCK = """\
    # Only this service builds: the image is reused by the others.
    build:
      context: .
      dockerfile: Simulator/Dockerfile
"""

DEPENDS_BLOCK = """\
    depends_on:
      - simulator-0
"""


def render(n: int, out: str, *, speed_scale: float, steering_sign: float,
           obs_latency: int, obs_lag_tau: float, steer_noise: float) -> str:
    n = max(1, n)
    parts = [HEADER.format(n=n, base=BASE_PORT, last=BASE_PORT + n - 1, out=out)]
    for i in range(n):
        parts.append(SERVICE.format(
            i=i,
            image=IMAGE_TAG,
            host_port=BASE_PORT + i,
            build=BUILD_BLOCK if i == 0 else "",
            depends="" if i == 0 else DEPENDS_BLOCK,
            speed_scale=speed_scale,
            steering_sign=steering_sign,
            obs_latency=obs_latency,
            obs_lag_tau=obs_lag_tau,
            steer_noise=steer_noise,
        ))
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("n", nargs="?", type=int,
                    default=int(os.getenv("NUM_WORKERS", "4")),
                    help="numero di worker (default: NUM_WORKERS env o 4)")
    ap.add_argument("--out", default="docker-compose.c2.parallel.yml")
    ap.add_argument("--speed-scale", type=float, default=1.0, dest="speed_scale",
                    help="taratura del punto operativo (§7.1)")
    ap.add_argument("--steering-sign", type=float, default=-1.0, dest="steering_sign",
                    help="gate V3; -1.0 è il valore misurato corretto per Unity")
    ap.add_argument("--obs-latency", type=int, default=0, dest="obs_latency")
    ap.add_argument("--obs-lag-tau", type=float, default=0.0, dest="obs_lag_tau")
    ap.add_argument("--steer-noise", type=float, default=0.0, dest="steer_noise")
    args = ap.parse_args()

    text = render(args.n, args.out, speed_scale=args.speed_scale,
                  steering_sign=args.steering_sign, obs_latency=args.obs_latency,
                  obs_lag_tau=args.obs_lag_tau, steer_noise=args.steer_noise)
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), args.out)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    print(f"Wrote {path} with {args.n} worker(s) "
          f"(ports {BASE_PORT}-{BASE_PORT + args.n - 1}).")
    print(f"Start with:  docker compose -f {args.out} up --build")
    print(f"Then run the client with:  NUM_WORKERS={args.n}")


if __name__ == "__main__":
    main()
